### ISSUE TITLE
Yellow guidance lines at 25%, 50% and 75% don't render at certain resolutions

### ISSUE THREAD

**Issue by BendyWalker** [BendyWalker/Alignment-Grid#4]
The logic used to display the guidance lines is a little fragile. If the number of lines doesn't divide cleanly by 4, then the yellow line is not rendered.
```
if index == (numberOfLines * 0.5) then
    line:SetColorTexture(1, 1, 0, 0.75)
elseif ((index == (numberOfLines * 0.25)) or (index == (numberOfLines * 0.75))) then
    line:SetColorTexture(1, 1, 0, 0.5)
else
    line:SetColorTexture(1, 1, 1, 0.25)
end
```
Figure out a better approach to rendering these lines that works for displays of any resolution.

**Comment by BendyWalker** [comment]
Reconsider using @m4xc4v413r4's approach detailed [here](https://github.com/BendyWalker/Alignment-Grid/issues/1#issuecomment-524338040).

**Comment by m4xc4v413r4** [comment]
I used my code but you can do it on yours, just take the math i used to get the middle lines and the quarter lines and change the color with that.

https://repl.it/repls/WarlikeDarkkhakiPup
